title: <img src="/images/austin_poole.png" alt="Austin Poole" />
logo: "/images/logo_overlay.png?raw=true" 
email: austtp25@gmail.com
description: > 
  <br >
  <span id="description">I'm a data science graduate student at Bellevue University.</span>
  <h2 style="margin: 1em 0 1em 0; letter-spacing: -0.1px;" id="menu"><a href="/">About</a> &nbsp;<img src="images/bullet_post.png" alt="Bullet Post" />&nbsp; <a href="/work">Work</a> &nbsp;<img src="images/bullet_post.png" alt="Bullet Post" />&nbsp; <a href="/contact">Contact</a></h2>
  <a href="http://www.linkedin.com/in/austinpoole/" id="linkedin">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-162006423-1
