name: Austin Poole
title: <img src="/images/austin_poole.png" alt="Austin Poole" />
logo: "/images/logo_overlay.png?raw=true" 
email: austtp25@gmail.com
description: I'm a data science graduate student at Bellevue University.
theme: jekyll-theme-minimal
google_analytics: UA-162006423-1
disqus: austtp86
comments: true
baseurl: "/austtp.github.io"

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://austtp.github.io

# The release of Jekyll Now that you're using
version: v1.2.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

markdown: kramdown
theme: minima
gems:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html

# Explicitly turn off the old code
paginate: nil
paginate_path: nil

# Pagination Settings
pagination:
  enabled: true
  per_page: 2
  offset: 2
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
